name: CI
on:
push:
branches: [ main ]
pull_request:
branches: [ main ]
jobs:
validate:
runs-on: ubuntu-latest
steps:

- uses: actions/checkout@v2

# Example command, you might need to change this
- name: Lint
run: npm run lint

# Example command, you might need to change this
# - name: Tests
# run: npm run tests